version: "3"


networks:
  dash-net:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  app:
    build: .
    container_name: django-gunicorn
    restart: always
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 project.wsgi:application"
    volumes:
      - ./static:/static
    networks:
      - dash-net

  nginx:
    image: nginx:1.14
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./static:/static
    depends_on:
      - app
    networks:
      - dash-net

